import { NextResponse } from "next/server"

interface ChatMessage {
  role: "user" | "assistant"
  content: string
}

// This API route provides a simple stubbed chat response.
// It echoes back the last user message and returns a couple of example suggestions.
export async function POST(req: Request) {
  const { messages }: { messages: ChatMessage[] } = await req.json()

  // Find the last user message to personalise the reply.
  const lastUser = messages?.filter((m) => m.role === "user").pop()?.content ?? ""

  // Stub assistant content.
  const content = `「${lastUser}」を受け取りました。チャット機能は現在スタブ応答です。`

  // Example suggestions. In a real implementation these would be generated by an AI model.
  const suggestions = [
    {
      type: "improvement",
      title: "説明の充実",
      description: "返答に背景説明を加えるとユーザーの理解が深まります。",
      confidence: Math.floor(Math.random() * 30) + 70,
      category: "応答品質",
    },
    {
      type: "opportunity",
      title: "関連コードの提示",
      description: "具体例となるコードスニペットを提示すると実装の助けになります。",
      confidence: Math.floor(Math.random() * 30) + 50,
      category: "ドキュメント",
    },
  ]

  return NextResponse.json({ content, suggestions })
}
